### ISSUE TITLE
Dash in projectname crashes Piereling client code

### ISSUE THREAD

**Issue by hayco** [proycon/piereling#2]
`clamclient.create()` crashes when trying to create a project which contains a `-` character:

```$ ./01-doc-to-folia.py 
Generated projectname: clariah-conversion2546116374648037985
Traceback (most recent call last):
  File "./01-doc-to-folia.py", line 32, in <module>
    pier.create(project)
  File "/home/jong/.local/lib/python3.7/site-packages/clam/common/client.py", line 228, in create
    return self.request(project + '/', 'PUT')
  File "/home/jong/.local/lib/python3.7/site-packages/clam/common/client.py", line 164, in request
    if data.errors:
AttributeError: 'bool' object has no attribute 'errors'```

**Comment by proycon** [comment]
Agreed, that's a weird and uninformative error. It's a CLAM issue indeed so I'll try to move this to that repo.
